SELECT
    ges.id AS ges_id,
    ges.id_reportEcho,
    ges.gestation_age,
    ges.trimestru,
    ges.dateMenstruation,
    ges.view_examination,
    ges.single_multiple_pregnancy,
    ges.single_multiple_pregnancy_description,
    ges.antecedent,
    ges.comment,
    ges.concluzion,
    ges.recommendation,
    ges.fetalPrezentation,
    ges.multiplePregnancy,
    bio.BPD,
    bio.BPD_age,
    bio.HC,
    bio.HC_age,
    bio.AC,
    bio.AC_age,
    bio.FL,
    bio.FL_age,
    bio.FetusCorresponds,
    cr.calloteCranium,
    cr.facialeProfile,
    cr.nasalBones,
    cr.nasalBones_dimens,
    cr.eyeball,
    cr.eyeball_desciption,
    cr.nasolabialTriangle,
    cr.nasolabialTriangle_description,
    cr.nasalFold,
    snc.hemispheres,
    snc.fissureSilvius,
    snc.corpCalos,
    snc.ventricularSystem,
    snc.ventricularSystem_description,
    snc.cavityPellucidSeptum,
    snc.choroidalPlex,
    snc.choroidalPlex_description,
    snc.cerebellum,
    snc.cerebellum_description,
    snc.vertebralColumn,
    snc.vertebralColumn_description,
    hrt.`position`,
    hrt.heartBeat,
    hrt.heartBeat_frequency,
    hrt.heartBeat_rhythm,
    hrt.pericordialCollections,
    hrt.planPatruCamere,
    hrt.planPatruCamere_description,
    hrt.ventricularEjectionPathLeft,
    hrt.ventricularEjectionPathLeft_description,
    hrt.ventricularEjectionPathRight,
    hrt.ventricularEjectionPathRight_description,
    hrt.intersectionVesselMagistral,
    hrt.intersectionVesselMagistral_description,
    hrt.planTreiVase,
    hrt.planTreiVase_description,
    hrt.archAorta,
    hrt.planBicav,
    th.pulmonaryAreas,
    th.pulmonaryAreas_description,
    th.pleuralCollections,
    th.diaphragm,
    abd.abdominalWall,
    abd.abdominalCollections,
    abd.stomach,
    abd.stomach_description,
    abd.abdominalOrgans,
    abd.cholecist,
    abd.cholecist_description,
    abd.intestine,
    abd.intestine_description,
    us.kidneys,
    us.kidneys_descriptions,
    us.ureter,
    us.ureter_descriptions,
    us.bladder,
    oth.externalGenitalOrgans,
    oth.externalGenitalOrgans_aspect,
    oth.extremities,
    oth.extremities_descriptions,
    oth.fetusMass,
    oth.placenta,
    oth.placentaLocalization,
    oth.placentaDegreeMaturation,
    oth.placentaDepth,
    oth.placentaStructure,
    oth.placentaStructure_descriptions,
    oth.umbilicalCordon,
    oth.umbilicalCordon_description,
    oth.insertionPlacenta,
    oth.amnioticIndex,
    oth.amnioticIndexAspect,
    oth.amnioticBedDepth,
    oth.cervix,
    oth.cervix_description,
    dop.ombilic_PI,
    dop.ombilic_RI,
    dop.ombilic_SD,
    dop.ombilic_flux,
    dop.cerebral_PI,
    dop.cerebral_RI,
    dop.cerebral_SD,
    dop.cerebral_flux,
    dop.uterRight_PI,
    dop.uterRight_RI,
    dop.uterRight_SD,
    dop.uterRight_flux,
    dop.uterLeft_PI,
    dop.uterLeft_RI,
    dop.uterLeft_SD,
    dop.uterLeft_flux,
    dop.ductVenos
FROM
    tableGestation2 AS ges
LEFT JOIN
    tableGestation2_biometry AS bio ON bio.id_reportEcho = ges.id_reportEcho
LEFT JOIN
    tableGestation2_cranium AS cr ON cr.id_reportEcho = ges.id_reportEcho
LEFT JOIN
    tableGestation2_SNC AS snc ON snc.id_reportEcho = ges.id_reportEcho
LEFT JOIN
    tableGestation2_heart AS hrt ON hrt.id_reportEcho = ges.id_reportEcho
LEFT JOIN
    tableGestation2_thorax AS th ON th.id_reportEcho = ges.id_reportEcho
LEFT JOIN
    tableGestation2_abdomen AS abd ON abd.id_reportEcho = ges.id_reportEcho
LEFT JOIN
    tableGestation2_urinarySystem AS us ON us.id_reportEcho = ges.id_reportEcho
LEFT JOIN
    tableGestation2_other AS oth ON oth.id_reportEcho = ges.id_reportEcho
LEFT JOIN
    tableGestation2_doppler AS dop ON dop.id_reportEcho = ges.id_reportEcho
WHERE
    ges.id_reportEcho = :id_reports